/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imatdesigntest;

/**
 *
 * @author agnesmardh
 */
public class BasketItemFixed extends javax.swing.JPanel {

	/**
	 * Creates new form BasketItemFixed
	 */
	public BasketItemFixed() {
		initComponents();
	}
        public BasketItemFixed(String name, String amount, String generalPrice, String totalPrice){
                initComponents();
                
                this.basketFixedAmountLabel.setText(amount);
                this.basketFixedGeneralLabel.setText(generalPrice);
                this.basketFixedNameLabel.setText(name);
                this.basketFixedPriceLabel.setText(totalPrice);
        }

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        basketFixedNameLabel = new javax.swing.JLabel();
        basketFixedAmountLabel = new javax.swing.JLabel();
        basketFixedGeneralLabel = new javax.swing.JLabel();
        basketFixedPriceLabel = new javax.swing.JLabel();

        jLabel1.setText("Varunamn");

        jLabel2.setText("Antal:");

        jLabel3.setText("á pris:");

        jLabel4.setText("Pris:");

        basketFixedNameLabel.setText("jLabel5");

        basketFixedAmountLabel.setText("jLabel6");

        basketFixedGeneralLabel.setText("jLabel7");

        basketFixedPriceLabel.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basketFixedNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basketFixedAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basketFixedGeneralLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basketFixedPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(basketFixedNameLabel)
                    .addComponent(basketFixedAmountLabel)
                    .addComponent(basketFixedGeneralLabel)
                    .addComponent(basketFixedPriceLabel))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel basketFixedAmountLabel;
    private javax.swing.JLabel basketFixedGeneralLabel;
    private javax.swing.JLabel basketFixedNameLabel;
    private javax.swing.JLabel basketFixedPriceLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
