/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imatdesigntest;

import com.sun.javafx.geom.Ellipse2D;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Product;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author Jakys
 */
public class ItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form ItemPanel
     */
    public ItemPanel() {
        initComponents();
    }
    public ItemPanel(Product product){
        initComponents();
        this.product = product;
        this.productNameLabel.setText(product.getName());
        this.productPriceLabel.setText(Double.toString(product.getPrice()));
        this.jLabel4.setText(product.getUnit());
       
        this.productImageLabel.setIcon(IMatDataHandler.getInstance().getImageIcon(product, 235,115));
        checkIfFavorite();
        this.spinnerPanel1.setQuantity(1);
    }
    public ItemPanel(Product product, boolean fav){
       this(product);
       this.fav = fav;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informationDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        addedDialog = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        denyDialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        productNameLabel = new javax.swing.JLabel();
        infoButton = new javax.swing.JButton();
        favoriteAddButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        addToCartButton = new javax.swing.JButton();
        productPriceLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spinnerPanel1 = new imatdesigntest.spinnerPanel();
        jPanel3 = new javax.swing.JPanel();
        productImageLabel = new javax.swing.JLabel();

        informationDialog.setBackground(new java.awt.Color(245, 245, 245));
        informationDialog.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        informationDialog.setForeground(new java.awt.Color(33, 33, 33));
        informationDialog.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        informationDialog.setType(java.awt.Window.Type.UTILITY);
        informationDialog.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                informationDialogFocusLost(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(245, 245, 245));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 33, 33));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Extra info table");
        jLabel1.setText("<html>Lorem ipsum dolor sit amet, c"
            + "onsecttur adipiscing elit, sed do eiusmod t"
            + "empor incididunt ut labore et dolore magna aliqua"
            + ". Ut enim ad minim veniam, quis nostrud exercita"
            + "tion ullamco laboris nisi ut aliquip ex ea comm"
            + "do consequat. Duis aute irure dolor in reprehenderi"
            + "t in voluptate velit esse cillum dolore eu fugiat n"
            + "ulla pariatur. Excepteur sint occaecat cupidatat non pro"
            + "ident, sunt in culpa qui officia deserunt mollit ani"
            + "m id est laborum.</html>");

        javax.swing.GroupLayout informationDialogLayout = new javax.swing.GroupLayout(informationDialog.getContentPane());
        informationDialog.getContentPane().setLayout(informationDialogLayout);
        informationDialogLayout.setHorizontalGroup(
            informationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        informationDialogLayout.setVerticalGroup(
            informationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        addedDialog.setMinimumSize(new java.awt.Dimension(202, 40));
        addedDialog.setUndecorated(true);
        addedDialog.setType(java.awt.Window.Type.UTILITY);

        jPanel5.setBackground(new java.awt.Color(52, 168, 83));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setBackground(new java.awt.Color(222, 222, 121));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(245, 245, 245));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Varan har lagts till i varukorgen!");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addedDialogLayout = new javax.swing.GroupLayout(addedDialog.getContentPane());
        addedDialog.getContentPane().setLayout(addedDialogLayout);
        addedDialogLayout.setHorizontalGroup(
            addedDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addedDialogLayout.setVerticalGroup(
            addedDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        denyDialog.setBackground(new java.awt.Color(255, 255, 153));
        denyDialog.setForeground(new java.awt.Color(255, 255, 153));
        denyDialog.setMinimumSize(new java.awt.Dimension(175, 40));
        denyDialog.setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(234, 67, 53));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setBackground(new java.awt.Color(234, 67, 53));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(245, 245, 245));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Kan inte lägga till 0st varor!");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout denyDialogLayout = new javax.swing.GroupLayout(denyDialog.getContentPane());
        denyDialog.getContentPane().setLayout(denyDialogLayout);
        denyDialogLayout.setHorizontalGroup(
            denyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        denyDialogLayout.setVerticalGroup(
            denyDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(denyDialogLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(33, 33, 33), 1, true));

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        productNameLabel.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        productNameLabel.setForeground(new java.awt.Color(33, 33, 33));
        productNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productNameLabel.setText("Varunamn");

        infoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatdesigntest/our_images/info.gif"))); // NOI18N
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        favoriteAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatdesigntest/our_images/star.gif"))); // NOI18N
        favoriteAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favoriteAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(productNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(favoriteAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(productNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(favoriteAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));

        addToCartButton.setBackground(new java.awt.Color(52, 168, 83));
        addToCartButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addToCartButton.setForeground(new java.awt.Color(245, 245, 245));
        addToCartButton.setText("Lägg till");
        addToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartButtonActionPerformed(evt);
            }
        });

        productPriceLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        productPriceLabel.setForeground(new java.awt.Color(234, 67, 53));
        productPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        productPriceLabel.setText("pris");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("kr/st");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spinnerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addToCartButton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(spinnerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(productPriceLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(addToCartButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        productImageLabel.setBackground(new java.awt.Color(255, 255, 255));
        productImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartButtonActionPerformed
        if( Double.parseDouble(spinnerPanel1.getQuantity()) <= 0 ){
            spawnCannotAddDialog();
        } else {
            
        
        sci = new ShoppingItem(product, Double.parseDouble(spinnerPanel1.getQuantity()));  
        
        IMatDataHandler.getInstance().getShoppingCart().addItem(sci);
        spinnerPanel1.setQuantity(0);
            spawnAddedDialog();
        }
    }//GEN-LAST:event_addToCartButtonActionPerformed

    private void favoriteAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favoriteAddButtonActionPerformed
        if (favoriteAddButton.getBackground() == Color.ORANGE){
            
            IMatDataHandler.getInstance().removeFavorite(product);
            favoriteAddButton.setBackground(Color.lightGray);
            this.favoriteAddButton.repaint();
            
            //[REFACTOR] Use this setup instead in basket item.
            if(fav){
                this.setVisible(false);  
                this.remove(this);
            }
           
        } else {
            IMatDataHandler.getInstance().addFavorite(product);
            favoriteAddButton.setBackground(Color.ORANGE);
        }
    }//GEN-LAST:event_favoriteAddButtonActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        informationDialog.setLocationRelativeTo(infoButton);
        informationDialog.setSize(this.getSize());
        informationDialog.setVisible(true);
        
    }//GEN-LAST:event_infoButtonActionPerformed

    private void informationDialogFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_informationDialogFocusLost
        informationDialog.dispose();
    }//GEN-LAST:event_informationDialogFocusLost
    
    private void checkIfFavorite(){
       for (Product p : IMatDataHandler.getInstance().favorites()){
           if (p.equals(product)) {
               favoriteAddButton.setBackground(Color.ORANGE);
               this.favoriteAddButton.repaint();
           }
       }
    }
    private void spawnCannotAddDialog(){
        Timer timer = new Timer(2000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                denyDialog.setVisible(false);
                denyDialog.dispose();
                
            }
        });
        denyDialog.setLocationRelativeTo(this.addToCartButton);
        denyDialog.setSize(160,36);
        timer.setRepeats(false);
        timer.start();
        denyDialog.setVisible(true);
        System.out.println("Dialog closed");
    }
    
    private void spawnAddedDialog(){
        Timer timer = new Timer(2000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
               addedDialog.setVisible(false);
               addedDialog.dispose();
                
            }
        });
        addedDialog.setLocationRelativeTo(this.addToCartButton);
        addedDialog.setSize(170,36);
        timer.setRepeats(false);
        timer.start();
        addedDialog.setVisible(true);
        System.out.println("Dialog closed");
    }
    public String getProductName(){
        return this.product.getName();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartButton;
    private javax.swing.JDialog addedDialog;
    private javax.swing.JDialog denyDialog;
    private javax.swing.JButton favoriteAddButton;
    private javax.swing.JButton infoButton;
    private javax.swing.JDialog informationDialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel productImageLabel;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JLabel productPriceLabel;
    private imatdesigntest.spinnerPanel spinnerPanel1;
    // End of variables declaration//GEN-END:variables
   private Product product;
   private ShoppingItem sci; //[REFACTOR TAG] change to anonymous!
   private boolean fav;
   
}
